import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ThemeProvider from "@/providers/theme-provider";
import { AuthProvider } from "@/providers/auth-provider";
import { SocketContextProvider } from "@/providers/socket-provider";

// const inter = Josefin_Sans({ subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      
      // className={inter.className}
      
      >
        {/* <AuthProvider> */}

        <ThemeProvider>
          {" "}
          <SocketContextProvider>{children}</SocketContextProvider>
        </ThemeProvider>
        {/* </AuthProvider> */}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
